In [20]:
import requests
import pandas as pd

In [21]:
url = "https://api.binance.com/api/v3/klines"

In [22]:
params = {
    "symbol": "BTCUSDT",
    "interval": "1h",
    "startTime": 1651363200000,  # unix timestamp
    "endTime": 1651449600000,
    "limit": 24
}

response = requests.get(url, params=params)
data = response.json()
data[:2]

[[1651363200000,
  '37630.80000000',
  '37806.79000000',
  '37500.00000000',
  '37680.67000000',
  '2313.83572000',
  1651366799999,
  '87126400.19490190',
  55934,
  '1052.75000000',
  '39653787.48505660',
  '0'],
 [1651366800000,
  '37680.66000000',
  '38077.10000000',
  '37386.38000000',
  '37937.07000000',
  '2622.65157000',
  1651370399999,
  '98898272.01292650',
  67090,
  '1278.10037000',
  '48222938.91877030',
  '0']]

In [23]:
#Binance requires the date in milliseconds (Unix timestamp format)
pd.Timestamp("2022-05-01").timestamp() * 1000

1651363200000.0

In [24]:
data[0]
#[open_time, open, high, low, close, volume, close_time, quote_volume, trades, taker_buy_base, taker_buy_quote, ignore]

[1651363200000,
 '37630.80000000',
 '37806.79000000',
 '37500.00000000',
 '37680.67000000',
 '2313.83572000',
 1651366799999,
 '87126400.19490190',
 55934,
 '1052.75000000',
 '39653787.48505660',
 '0']

In [25]:
df = pd.DataFrame(data, columns=[
    "open_time", "open", "high", "low", "close", "volume",
    "close_time", "quote_volume", "trades", "taker_buy_base", "taker_buy_quote", "ignore"
])
df.head()

,open_time,open,high,low,close,volume,close_time,quote_volume,trades,taker_buy_base,taker_buy_quote,ignore
0,1651363200000,37630.80000000,37806.79000000,37500.00000000,37680.67000000,2313.83572000,1651366799999,87126400.19490190,55934,1052.75000000,39653787.48505660,0
1,1651366800000,37680.66000000,38077.10000000,37386.38000000,37937.07000000,2622.65157000,1651370399999,98898272.01292650,67090,1278.10037000,48222938.91877030,0
2,1651370400000,37937.07000000,38053.68000000,37771.81000000,37817.79000000,1081.24561000,1651373999999,40999139.36637420,46800,539.34865000,20452299.72367900,0
3,1651374000000,37817.78000000,38064.39000000,37801.52000000,38041.44000000,966.53850000,1651377599999,36692953.62362710,37818,556.26797000,21116324.30872850,0
4,1651377600000,38041.44000000,38063.41000000,37885.30000000,37948.39000000,1405.77554000,1651381199999,53355755.52700410,44737,816.40505000,30975694.49125630,0

In [26]:
#return time to regular format
df["open_time"] = pd.to_datetime(df["open_time"], unit="ms")
df.head()

,open_time,open,high,low,close,volume,close_time,quote_volume,trades,taker_buy_base,taker_buy_quote,ignore
0,2022-05-01 00:00:00,37630.80000000,37806.79000000,37500.00000000,37680.67000000,2313.83572000,1651366799999,87126400.19490190,55934,1052.75000000,39653787.48505660,0
1,2022-05-01 01:00:00,37680.66000000,38077.10000000,37386.38000000,37937.07000000,2622.65157000,1651370399999,98898272.01292650,67090,1278.10037000,48222938.91877030,0
2,2022-05-01 02:00:00,37937.07000000,38053.68000000,37771.81000000,37817.79000000,1081.24561000,1651373999999,40999139.36637420,46800,539.34865000,20452299.72367900,0
3,2022-05-01 03:00:00,37817.78000000,38064.39000000,37801.52000000,38041.44000000,966.53850000,1651377599999,36692953.62362710,37818,556.26797000,21116324.30872850,0
4,2022-05-01 04:00:00,38041.44000000,38063.41000000,37885.30000000,37948.39000000,1405.77554000,1651381199999,53355755.52700410,44737,816.40505000,30975694.49125630,0

In [27]:
df = df[["open_time", "open", "high", "low", "close", "volume"]]
df[["open", "high", "low", "close", "volume"]] = df[["open", "high", "low", "close", "volume"]].astype(float)
df.head()

            open_time      open      high       low     close      volume
0 2022-05-01 00:00:00  37630.80  37806.79  37500.00  37680.67  2313.83572
1 2022-05-01 01:00:00  37680.66  38077.10  37386.38  37937.07  2622.65157
2 2022-05-01 02:00:00  37937.07  38053.68  37771.81  37817.79  1081.24561
3 2022-05-01 03:00:00  37817.78  38064.39  37801.52  38041.44   966.53850
4 2022-05-01 04:00:00  38041.44  38063.41  37885.30  37948.39  1405.77554

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   open_time  24 non-null     datetime64[ms]
 1   open       24 non-null     float64
 2   high       24 non-null     float64
 3   low        24 non-null     float64
 4   close      24 non-null     float64
 5   volume     24 non-null     float64
dtypes: datetime64[ms](1), float64(5)
memory usage: 1.3 KB

In [29]:
def get_binance_hourly(symbol, start_date, end_date):
    start_ts = int(pd.Timestamp(start_date).timestamp() * 1000)
    end_ts = int(pd.Timestamp(end_date).timestamp() * 1000)
    
    params = {"symbol": symbol, "interval": "1h", "startTime": start_ts, "endTime": end_ts, "limit": 1000}
    response = requests.get(url, params=params)
    data = response.json()
    
    df = pd.DataFrame(data, columns=[
        "open_time", "open", "high", "low", "close", "volume",
        "close_time", "quote_volume", "trades", "taker_buy_base", "taker_buy_quote", "ignore"
    ])
    df["open_time"] = pd.to_datetime(df["open_time"], unit="ms")
    df = df[["open_time", "open", "high", "low", "close", "volume"]]
    df[["open", "high", "low", "close", "volume"]] = df[["open", "high", "low", "close", "volume"]].astype(float)
    return df

In [30]:
btc_luna_hourly = get_binance_hourly("BTCUSDT", "2022-04-29", "2022-05-29")
btc_luna_hourly.head()

            open_time      open      high       low     close      volume
0 2022-04-29 00:00:00  39742.06  39869.28  39675.46  39845.00  1133.07982
1 2022-04-29 01:00:00  39844.99  39925.25  39769.98  39820.48  1087.33563
2 2022-04-29 02:00:00  39820.47  39831.85  39457.13  39522.12  1776.65661
3 2022-04-29 03:00:00  39522.12  39557.87  39286.01  39533.01  1777.88524
4 2022-04-29 04:00:00  39533.02  39598.30  39368.97  39542.94  1436.13149

In [31]:
btc_luna_hourly.shape

(721, 6)

In [46]:
btc_luna_hourly.to_csv("data/raw/hourly/btc_luna_hourly.csv", index=False)

In [47]:
eth_luna_hourly = get_binance_hourly("ETHUSDT", "2022-04-29", "2022-05-29")

In [48]:
eth_luna_hourly.head()

            open_time     open     high      low    close      volume
0 2022-04-29 00:00:00  2936.92  2946.46  2925.70  2943.74  11812.7215
1 2022-04-29 01:00:00  2943.74  2944.83  2927.45  2931.65  14020.1453
2 2022-04-29 02:00:00  2931.66  2936.35  2905.65  2911.17  22438.7470
3 2022-04-29 03:00:00  2911.17  2928.21  2904.14  2926.21  17850.9927
4 2022-04-29 04:00:00  2926.21  2927.14  2909.61  2920.01  13914.1666

In [49]:
eth_luna_hourly.shape

(721, 6)

In [50]:
eth_luna_hourly.to_csv("data/raw/hourly/eth_luna_hourly.csv", index=False)

In [ ]:
btc_celsius_hourly = get_binance_hourly("BTCUSDT", "2022-06-03", "2022-07-03")

In [34]:
btc_celsius_hourly.head()

            open_time      open      high       low     close      volume
0 2022-06-03 00:00:00  30452.63  30515.20  30359.54  30401.53  1755.69048
1 2022-06-03 01:00:00  30401.53  30699.00  30384.92  30628.38  2067.01970
2 2022-06-03 02:00:00  30628.39  30667.33  30532.34  30549.76  1105.54346
3 2022-06-03 03:00:00  30549.77  30562.15  30468.17  30529.96  1115.90936
4 2022-06-03 04:00:00  30529.96  30547.20  30422.62  30425.00  1199.14326

In [35]:
btc_celsius_hourly.isna().sum()

open_time    0
open         0
high         0
low          0
close        0
volume       0
dtype: int64

In [40]:
btc_celsius_hourly.shape

(721, 6)

In [51]:
btc_celsius_hourly.to_csv("data/raw/hourly/btc_celsius_hourly.csv", index=False)

In [36]:
eth_celsius_hourly = get_binance_hourly("ETHUSDT", "2022-06-03", "2022-07-03")

In [37]:
eth_celsius_hourly.head()

            open_time     open     high      low    close      volume
0 2022-06-03 00:00:00  1834.09  1835.79  1822.30  1825.49  21581.6474
1 2022-06-03 01:00:00  1825.49  1843.91  1824.64  1840.21  25383.8880
2 2022-06-03 02:00:00  1840.21  1843.34  1831.19  1831.37  15709.9605
3 2022-06-03 03:00:00  1831.37  1833.24  1826.84  1827.52  17421.2910
4 2022-06-03 04:00:00  1827.51  1829.10  1816.67  1816.82  18409.5955

In [38]:
eth_celsius_hourly.isna().sum()

open_time    0
open         0
high         0
low          0
close        0
volume       0
dtype: int64

In [39]:
eth_celsius_hourly.shape

(721, 6)

In [52]:
eth_celsius_hourly.to_csv("data/raw/hourly/eth_celsius_hourly.csv", index=False)

In [42]:
btc_signature_hourly = get_binance_hourly("BTCUSDT", "2023-02-27", "2023-03-29")
btc_signature_hourly.head()

            open_time      open      high       low     close      volume
0 2023-02-27 00:00:00  23554.85  23567.69  23451.66  23492.64  7993.69860
1 2023-02-27 01:00:00  23492.15  23563.00  23432.76  23552.76  7112.75383
2 2023-02-27 02:00:00  23553.52  23644.65  23522.72  23558.64  7388.93825
3 2023-02-27 03:00:00  23558.64  23642.00  23540.74  23551.62  8297.11995
4 2023-02-27 04:00:00  23551.99  23561.34  23463.47  23491.46  7628.19288

In [44]:
btc_signature_hourly.isna().sum()

open_time    0
open         0
high         0
low          0
close        0
volume       0
dtype: int64

In [45]:
btc_signature_hourly.shape

(720, 6)

In [53]:
btc_signature_hourly.to_csv("data/raw/hourly/btc_signature_hourly.csv", index=False)

In [54]:
eth_signature_hourly = get_binance_hourly("ETHUSDT", "2023-02-27", "2023-03-29")
eth_signature_hourly.head()

            open_time     open     high      low    close      volume
0 2023-02-27 00:00:00  1641.37  1641.75  1635.47  1637.47  12090.3427
1 2023-02-27 01:00:00  1637.48  1643.89  1632.06  1643.36  11630.3632
2 2023-02-27 02:00:00  1643.35  1650.91  1639.28  1640.81  16265.8863
3 2023-02-27 03:00:00  1640.80  1646.10  1639.37  1640.67  13787.3311
4 2023-02-27 04:00:00  1640.68  1641.08  1635.00  1635.50  11479.7852

In [55]:
eth_signature_hourly.isna().sum()

open_time    0
open         0
high         0
low          0
close        0
volume       0
dtype: int64

In [56]:
eth_signature_hourly.shape

(720, 6)

In [57]:
eth_signature_hourly.to_csv("data/raw/hourly/eth_signature_hourly.csv", index=False)